export const colleges = [
  "National Institute of Technology Calicut",
  "ER&DCI Institute of Technology, Trivandrum",
  "National Institute of Electronics & Information Technology, Calicut",
  "Indian Institute of Space Science and Technology, Trivandrum",
  "Indian Institute of Information Technology Kottayam",
  "Indian Institute of Technology Palakkad",
  "IISER Thiruvananthapuram",
  "Sree Chitra Tirunal Institute for Medical Sciences and Technology, Trivandrum",
  "College of Engineering, Trivandrum",
  "Government Engineering College, Thrissur",
  "Thangal Kunju Musaliar College of Engineering, Kollam",
  "NSS College of Engineering, Palakkad",
  "Mar Athanasius College of Engineering, Kothamangalam",
  "Government College of Engineering, Kannur",
  "Rajiv Gandhi Institute of Technology, Kottayam",
  "Government Engineering College, Sreekrishnapuram",
  "Government Engineering College, Trivandrum (Barton Hill)",
  "Government Engineering College, Kozhikode",
  "Government Engineering College, Wayanad",
  "Government Engineering College, Idukki",
  "Government Model Engineering College, Cochin",
  "College of Engineering Chengannur",
  "LBS College of Engineering, Kasaragod",
  "LBS Institute of Technology for Women, Trivandrum",
  "College of Engineering Attingal",
  "College of Engineering Cherthala",
  "College of Engineering Kallooppara",
  "College of Engineering Karunagappally",
  "College of Engineering Kottarakkara",
  "College of Engineering Poonjar",
  "College of Engineering Aranmula",
  "College of Engineering Kidangoor",
  "College of Engineering & Management Punnapra",
  "College of Engineering Pathanapuram",
  "College of Engineering Perumon",
  "College of Engineering Thalassery",
  "College of Engineering Thrikaripur",
  "College of Engineering Vatakara",
  "College of Engineering Muttathara",
  "College of Engineering Munnar",
  "College of Engineering Adoor",
  "Sree Chitra Thirunal College of Engineering, Trivandrum",
  "School of Engineering, CUSAT",
  "Cochin University College of Engineering Kuttanad",
  "CUIET Tenhipalam",
  "University College of Engineering Kariavattom",
  "University College of Engineering Thodupuzha",
  "Kelappaji College of Agricultural Engineering and Technology",
  "ACE College of Engineering",
  "Adi Shankara Institute of Engineering Technology",
  "Ahalia School of Engineering and Technology",
  "Al Azhar College of Engineering and Technology",
  "Al-Ameen Engineering College",
  "Albertian Institute of Science and Technology",
  "Amal Jyothi College of Engineering",
  "Ammini College of Engineering",
  "Archana College of Engineering",
  "Aryanet Institute of Technology",
  "AWH Engineering College",
  "Axis College of Engineering and Technology",
  "Baselios Mathews II College of Engineering",
  "Baselios Thomas I Catholicose College of Engineering and Technology",
  "Caarmel Engineering College",
  "Bishop Jerome Institute",
  "Carmel College of Engineering and Technology",
  "Christ College of Engineering Irinjalakuda",
  "Christ Knowledge City",
  "Cochin College of Engineering and Technology",
  "Cochin Institute of Science and Technology",
  "College of Engineering Kannur (CEN?)",
  "Ernad Knowledge City Technical Campus",
  "Federal Institute of Science and Technology",
  "College of Engineering Poomala (FOP)",
  "Gurudeva Institute of Science and Technology",
  "Heera College of Engineering and Technology",
  "Hindustan College of Engineering",
  "Holy Grace Academy of Engineering",
  "Holy Kings College of Engineering and Technology",
  "IES College of Engineering",
  "Ilahia College of Engineering & Technology",
  "Ilahia School of Science and Technology",
  "ILM College of Engineering and Technology",
  "Indira Gandhi Institute of Engineering & Technology for Women",
  "Jai Bharath College of Management and Engineering Technology",
  "Jawaharlal College of Engineering and Technology",
  "John Cox Memorial CSI Institute of Technology",
  "Jyothi Engineering College",
  "KMEA Engineering College",
  "Gouri Amma College of Engineering for Women",
  "KMCT College of Engineering",
  "KMCT College of Engineering for Women",
  "KMCT Polytechnic? (skip non engg)",
  "Kottayam Institute of Technology & Science",
  "KVM College of Engineering and IT",
  "Lourdes Matha College of Science and Technology",
  "MEA Engineering College",
  "MES College of Engineering",
  "MG College of Engineering",
  "M. Dasan Institute of Technology",
  "Malabar College of Engineering and Technology",
  "Malabar Institute of Technology",
  "Mangalam College of Engineering",
  "Mar Baselios Christian College of Engineering and Technology",
  "Mar Baselios College of Engineering and Technology",
  "Mar Baselios Institute of Technology and Science",
  "Matha College of Technology",
  "MES Engineering College Kunnukara",
  "MES Institute of Technology and Management",
  "MET School of Engineering",
  "Mohandas College of Engineering and Technology",
  "Mookambika Technical Campus",
  "Mount Zion College of Engineering",
  "Mount Zion College of Engineering for Women",
  "Musaliar College of Engineering Chirayinkeezhu",
  "Musaliar College of Engineering and Technology",
  "Muslim Association College of Engineering",
  "Muthoot Institute of Technology and Science",
  "Nehru College of Engineering and Research Centre",
  "Nirmala College of Engineering",
  "North Malabar Institute of Technology",
  "Pinnacle School of Engineering and Technology",
  "Prime College of Engineering",
  "Providence College of Engineering",
  "PRS College of Engineering and Technology",
  "Rajadhani Institute of Engineering and Technology",
  "Rajagiri School of Engineering and Technology",
  "Royal College of Engineering and Technology",
  "SNGM College of Engineering",
  "Sahrdaya College of Engineering and Technology",
  "Saintgits College of Engineering",
  "Sarabhai Institute of Science and Technology",
  "SCMS School of Engineering and Technology",
  "Shahul Hameed Memorial Engineering College",
  "SNM Institute of Management and Technology",
  "Sree Buddha College of Engineering",
  "Sree Buddha College of Engineering for Women",
  "Sree Ernakulathappan College of Engineering and Management",
  "Sree Narayana Guru College of Engineering and Technology",
  "Sree Narayana Guru Institute of Science and Technology",
  "Sree Narayana Gurukulam College of Engineering",
  "Sree Narayana Institute of Technology",
  "Sreepathy Institute of Management and Technology",
  "Sri Vellappally Natesan College of Engineering",
  "St. Gregorios College of Engineering",
  "St. Joseph's College of Engineering and Technology",
  "St. Thomas College of Engineering and Technology (Kannur)",
  "St. Thomas College of Engineering and Technology (Chengannur)",
  "St. Thomas Institute for Science & Technology",
  "TKM Institute of Technology",
  "Thejus Engineering College",
  "Toc H Institute of Science and Technology",
  "Toms College of Engineering for Startups",
  "Travancore Engineering College",
  "Trinity College of Engineering",
  "UKF College of Engineering and Technology",
  "Universal Engineering College",
  "Valia Koonambaikulathamma College of Engineering and Technology",
  "Vedavyasa Institute of Technology",
  "Vidya Academy of Science and Technology",
  "Vidya Academy of Science and Technology Technical Campus",
  "VISAT Engineering College",
  "Vimal Jyothi Engineering College",
  "Viswajyothi College of Engineering and Technology",
  "Younus College of Engineering",
  "Younus College of Engineering & Technology",
  "Younus Institute of Technology",
  "Other",
];
